$primary_paletteKeyColor = 777777
$secondary_paletteKeyColor = 777777
$tertiary_paletteKeyColor = 787776
$neutral_paletteKeyColor = 777777
$neutral_variant_paletteKeyColor = 777777
$background = 050505
$onBackground = e2e2e2
$surface = 050505
$surfaceDim = 050505
$surfaceBright = 101010
$surfaceContainerLowest = 030303
$surfaceContainerLow = 070707
$surfaceContainer = 090909
$surfaceContainerHigh = 0c0c0c
$surfaceContainerHighest = 0f0f0f
$onSurface = e2e2e2
$surfaceVariant = 131313
$onSurfaceVariant = c6c6c6
$inverseSurface = e2e2e2
$inverseOnSurface = 313131
$outline = 919191
$outlineVariant = 474747
$shadow = 000000
$scrim = 000000
$surfaceTint = 282828
$primary = c6c6c6
$onPrimary = 303030
$primaryContainer = 474747
$onPrimaryContainer = e2e2e2
$inversePrimary = 5e5e5e
$secondary = c7c7c7
$onSecondary = 303030
$secondaryContainer = 474747
$onSecondaryContainer = e3e3e3
$tertiary = c8c6c5
$onTertiary = 303130
$tertiaryContainer = 929090
$onTertiaryContainer = 000000
$error = e4beb9
$onError = 601410
$errorContainer = 891c18
$onErrorContainer = e2e2e2
$primaryFixed = e2e2e2
$primaryFixedDim = c6c6c6
$onPrimaryFixed = 1b1b1b
$onPrimaryFixedVariant = 474747
$secondaryFixed = e3e3e3
$secondaryFixedDim = c7c7c7
$onSecondaryFixed = 1b1b1b
$onSecondaryFixedVariant = 474747
$tertiaryFixed = e4e2e1
$tertiaryFixedDim = c8c6c5
$onTertiaryFixed = 1b1b1b
$onTertiaryFixedVariant = 474646
$term0 = 080808
$term1 = 7d9c38
$term2 = 8cdbc2
$term3 = acf5d5
$term4 = 97b0ad
$term5 = 92adcf
$term6 = a8d2c8
$term7 = d8d8d8
$term8 = a2a2a2
$term9 = 8eb63f
$term10 = 89f0d2
$term11 = e9f8ee
$term12 = bec2c0
$term13 = b2bfdc
$term14 = b3e6d9
$term15 = ffffff
$rosewater = f2f2f2
$flamingo = e2e2e2
$pink = d2deea
$mauve = 90c9d8
$red = 9db5e2
$maroon = b7bed5
$peach = bed4bc
$yellow = ecf3ee
$green = b6ebde
$teal = c3e7e2
$sky = bae3e2
$sapphire = 9dd0d2
$blue = 8bc7ce
$lavender = acd4da
$klink = 589095
$klinkSelection = 589095
$kvisited = 548799
$kvisitedSelection = 548799
$knegative = 858e39
$knegativeSelection = 858e39
$kneutral = 60be6d
$kneutralSelection = 60be6d
$kpositive = 66b7ab
$kpositiveSelection = 66b7ab
$text = e2e2e2
$subtext1 = c6c6c6
$subtext0 = 919191
$overlay2 = 1c1c1c
$overlay1 = 191919
$overlay0 = 161616
$surface2 = 121212
$surface1 = 0d0d0d
$surface0 = 060606
$base = 010101
$mantle = 010101
$crust = 010101
$success = B5CCBA
$onSuccess = 213528
$successContainer = 374B3E
$onSuccessContainer = D1E9D6
