foreground              #ece1d4
background              #241f17
selection_foreground    #f7dfbb
selection_background    #54452a

cursor                  #edc06c
cursor_text_color       #412d00

url_color               #b3cea7

active_border_color     #edc06c
inactive_border_color   #4e4639
bell_border_color       #ffb4ab

wayland_titlebar_color  system
macos_titlebar_color    system

active_tab_foreground   #ffdea6
active_tab_background   #5e4200
inactive_tab_foreground #d1c5b4
inactive_tab_background #241f17
tab_bar_background      #17130b

mark1_foreground #412d00
mark1_background #edc06c
mark2_foreground #3c2e15
mark2_background #dac4a0
mark3_foreground #1f361a
mark3_background #b3cea7

color0 #4e4639
color8 #9a8f80

color1 #ffb4ab
color9 #93000a

color2  #edc06c
color10 #ffdea6

color3  #b3cea7
color11 #ceebc1

color4  #dac4a0
color12 #f7dfbb

color5  #5e4200
color13 #7a590c

color6  #54452a
color14 #354d2e

color7  #d1c5b4
color15 #ece1d4
