[Appearance]
icon_theme=Papirus-Dark
color_scheme_path=/home/shalyn42k/.config/qt5ct/colors/matugen.conf
custom_palette=true
standard_dialogs=default
style=Fusion
stylesheets=/home/shalyn42k/.config/qt5ct/qss/matugen-style.qss

[Interface]
stylesheets=/home/shalyn42k/.config/qt5ct/qss/matugen-style.qss
